### PR TITLE
fixes #1, fixes archives sidebar styling

### LINKED ISSUE #1: Inconsistent Sidebar Styles
- All titles in the sidebar should have `monospace` style font
- All bullets should be unfilled circles.
### Screenshot:

sidebar styles
#### Steps to reproduce:
1. as admin login and create at least one article
2. proceed to localhost:3000 and view the article 
3. on the right side observe the font for Archives differs from the other headers
4. on the right side observe that the bullet points under archives are filled circles
#### Expected behavior:
1. Archives font should be monotype
2. Archives bullets should use unfilled-circle

### PR DESCRIPTION
**Pull request by billhimmelsbach**
fixes issue #1: fixes a typo when defining the class of the h3 tag and the div in the archive_sidebar partial, changes _ to -

Changes to:

```
  <h3 class="sidebar-title"><%= sidebar.title %></h3>
  <div class="sidebar-body">
```

From:

```
  <h3 class="sidebar_title"><%= sidebar.title %></h3>
  <div class="sidebar_body">
```

### CODE REVIEW

**Comment by justincastilla** [comment]
Please include in the comment the code that has been changed.

**Comment by billhimmelsbach** [comment]
<h3 class="sidebar-title"><%= sidebar.title %></h3>
  <div class="sidebar-body">

**Comment by billhimmelsbach** [comment]
> <h3 class="sidebar-title"><%= sidebar.title %></h3>
>   <div class="sidebar-body">

**Comment by billhimmelsbach** [comment]
```
  <h3 class="sidebar-title"><%= sidebar.title %></h3>
  <div class="sidebar-body">
```

**Comment by justincastilla** [comment]
Include all pull request content changes in the initial comment field.

**Comment by billhimmelsbach** [comment]
Adds content changes to original comment

**Comment by billhimmelsbach** [comment]
Adds original code for reference

**Comment by billhimmelsbach** [comment]
Thanks Justin!

**Comment by justincastilla** [comment]
Pull request accepted. PROTIP: include a link to the issue you are solving in your pull request comment by simply referencing it with a number symbol preceding the associated number: #1

**Pull request closed without merging**
