### PR TITLE
fixes #2, Top Month Always Empty (Archive Sidebar)

### LINKED ISSUE #2: Top Month Always Empty (Archive Sidebar)
- When I click on the top-most month in the Archive Sidebar it says "No posts found...".
- When I create a post in the _current month_ (e.g. February) it displays a link in the sidebar for _next month_ (e.g. March), and says "No posts found..."

### PR DESCRIPTION
**Pull request by billhimmelsbach**
**fixes** issue #2 : fixes an off by one error in the archives_sidebar model, changes month-1 to month-2.

Changes in lib/archives_sidebar/lib/archives_sidebar.rb:

```
month: month - 2,
```

From:

```
month: month - 1,
```

### CODE REVIEW

**Comment by billhimmelsbach** [comment]
Is it because they use a modulus and you can't divide by 0?

**Comment by billhimmelsbach** [comment]
Is this an issue with the change I made or my lack of initial explanation?

**Comment by melicarls** [comment]
It's the lack of initial explanation. Add an explanation to the original comment, please.

**Comment by billhimmelsbach** [comment]
Added explanation to original comment.

**Comment by billhimmelsbach** [comment]
Simplified explanation: it's an off by one error in the months path.

**Comment by justincastilla** [comment]
What about December?

**Comment by billhimmelsbach** [comment]
Reopens issue, found real source of the problem.

**Comment by billhimmelsbach** [comment]
Or maybe not? Unclear, this problem at the very least solves the routing issues for all except the top month. Will continue to investigate.

**Comment by billhimmelsbach** [comment]
Hi @nathanallen and @melicarls! Hope it's ok to close this PR. 😉   Hope y'all are doing great! 🎉

**Pull request closed without merging**
